name: VoicePlus
main: us.mcthemeparks.VoicePlus
version: 0.0.1
author: Clarkcj (Corey)
description: A basic voice server information plugin
commands:
    teamspeak:
        description: Command to show where to download TeamSpeak
        alias: ts
        usage: /<command>
    voiceinfo:
        description: Command to show server information for Mumble.
        alias: vi
        usage: /<command>
    voiceplus:
        description: Command to show where to download Mumble.
        alias: vp
        usage: /<command>
